import { Network } from '../multiplayer/network';
import { type GameState,chapters,aligned,desired,flowerPosition,vineAligned,vineHeights } from '../simulation/state';
import type { Sound } from '../audio/sound';

export class UI {
 mode:'title'|'join'|'room'|'play'|'pause'|'controls'|'ending'='title';root=document.querySelector<HTMLDivElement>('#ui')!;toastText='';toastUntil=0;debug=false;private signature='';private lastRefresh=0;
 onResume=()=>{};onRespawn=()=>{};onExit=()=>{};
 constructor(public net:Network,public sound:Sound){this.root.innerHTML='<div class="loading"><h2>The Glasshouse Lesson</h2><p>PREPARING THE ATELIER</p></div>';}
 get menu(){return this.mode!=='play';}
 render(force=false){
  const s=this.net.state;if(s?.phase==='playing'&&(this.mode==='room'||this.mode==='ending')){this.mode='play';this.onResume();}if(s?.phase==='ending')this.mode='ending';if(s?.phase==='lobby'&&['play','ending','pause'].includes(this.mode))this.mode='room';
  if(s?.paused||this.net.status==='disconnected'){if(this.mode==='play')this.mode='pause';}
  const signature=JSON.stringify([this.mode,this.net.status,this.net.error,s?.phase,s?.players.map(p=>[p.role,p.ready]),this.net.code]);if(!force&&signature===this.signature)return;this.signature=signature;
  const wrap=(content:string)=>`<div class="menu"><div class="menu-content">${content}</div><div class="bottom-note"><span>A TWO-PLAYER ADVENTURE</span><span>CHAPTER ONE</span></div><div class="edition">A little magic goes a long way.</div></div>`;
  const eyebrow='<div class="eyebrow">Field notes from a magical atelier</div>';
  if(this.mode==='title')this.root.innerHTML=wrap(`${eyebrow}<h1>The Glasshouse<br><em>Lesson</em></h1><p class="intro">Two apprentices. One simple task.<br>A rather extraordinary amount of growth.</p><button class="primary" id="create">Create a lesson <span>↗</span></button><button class="secondary" id="join">Join a friend <span>↗</span></button><div class="flourish">✧</div><p class="small-note">An online adventure for exactly two.<br>Bring a friend, a keyboard, and a little curiosity.</p><button class="text-button" id="controls">How to play</button>`);
  if(this.mode==='join')this.root.innerHTML=wrap(`${eyebrow}<h2>A lesson is better<br>with company.</h2><p>Enter the six-character code from your friend.</p><div class="join-row"><input id="room-input" aria-label="Room code" maxlength="6" placeholder="ABCDEF" autocomplete="off" spellcheck="false" value="${new URLSearchParams(location.search).get('room')?.replace(/[^a-zA-Z0-9]/g,'').slice(0,6)??''}"></div><button class="primary" id="connect">Join the lesson <span>↗</span></button><p class="status">${this.net.error}</p><button class="text-button" id="back">Back to title</button>`);
  if(this.mode==='room'){
   const roles=s?.players??[];this.root.innerHTML=wrap(`${eyebrow}<h2>Your workbench<br>for two.</h2><div class="eyebrow">Room code</div><div class="room-code">${this.net.code}</div><div class="room-actions"><button class="text-button" id="copy">Copy invite link</button><button class="text-button" id="copy-code">Copy code</button></div><div class="roles">${[0,1].map(i=>{const p=roles[i];return `<div class="role-row"><div class="role-symbol">${p?.role==='Warden'?'❧':'◇'}</div><div><div class="role-name">${p?.role??'An empty stool'}</div><div class="role-detail">${p?(p.id===this.net.id?'You':'Your friend')+(p.role==='Shaper'?' · Form & direction':' · Life & growth'):'Waiting for your friend'}</div></div><div class="ready-status">${p?.ready?'READY':p?'CHOOSING':''}</div></div>`;}).join('')}</div><button class="secondary" id="swap" ${roles.length<1?'disabled':''}>Swap disciplines <span>⇄</span></button><button class="primary" id="ready" ${roles.length!==2?'disabled':''}>${this.net.local?.ready?'Not ready yet':'I’m ready'} <span>✓</span></button>${this.net.host?`<button class="primary" id="start" ${roles.length!==2||!roles.every(p=>p.ready)?'disabled':''}>Begin the lesson <span>→</span></button>`:''}<p class="status">${this.net.error||(this.net.status==='connected'?(this.net.host?'Choose your studies, then begin.':'Your host will begin when you are both ready.'):'Pulling up a second stool…')}</p><button class="text-button" id="leave">Leave room</button>`);
  }
  if(this.mode==='play')this.root.innerHTML=`<div class="hud-top"><div class="eyebrow" id="chapter"></div><div class="objective" id="objective"></div></div><div class="partner"><span class="dot"></span><span id="partner-info">Two apprentices</span></div><div class="hud-bottom"><span class="role-symbol">${this.net.local?.role==='Warden'?'❧':'◇'}</span><span class="discipline">${this.net.local?.role}</span></div><div class="hint" id="hint"></div><div class="partner-tag" id="partner-tag">Your friend</div><button class="pause-button" id="pause">Esc · Field notes</button><div id="toast"></div><div id="debug"></div>`;
  if(this.mode==='pause'||this.mode==='controls')this.root.innerHTML=wrap(`${eyebrow}<h2>${this.mode==='pause'?'Take a breath.':'A little field guide.'}</h2><div class="controls-grid"><strong>W A S D</strong><span>Move · both apprentices run equally</span><strong>Space / Shift</strong><span>Jump / dash</span><strong>Right mouse drag</strong><span>Turn the camera</span><strong>Left mouse / R</strong><span>Spark · chimes, droplets, seals</span><strong>Hold E</strong><span>Shape or Bloom</span><strong>E + A / D</strong><span>Shaper: guide / rotate / move</span><strong>E + W / S</strong><span>Warden: raise / lower flower or vine</span><strong>Q / F</strong><span>Arcane Hand / partner ping</span></div><p class="small-note">Magic follows two rules: Shape decides where. Bloom decides what grows. Stand near a mechanism and hold E. Look for the brass guides. There are no lives to lose.</p><div class="settings"><label for="volume">Sound</label><input id="volume" type="range" min="0" max="1" step=".05" value="${this.sound.volume}"></div><p class="status">${this.net.error}</p><button class="primary" id="resume">${this.mode==='controls'?'Back':'Return to the lesson'} <span>→</span></button>${this.mode==='pause'?'<button class="secondary" id="respawn">Return to safe ground <span>↺</span></button><button class="text-button" id="return-room">Return both players to the room</button><br><button class="text-button" id="leave">Leave lesson</button>':''}`);
  if(this.mode==='ending')this.root.innerHTML=wrap(`${eyebrow}<div class="flourish">❧</div><h1>A little<br><em>overwatered.</em></h1><p>The glasshouse is mended.<br>The plants are extremely grateful.<br>The ceiling may need some attention.</p><div class="divider"></div><p style="font-family:Georgia;font-style:italic;color:#efdcba">“Good. Now try the small watering can.”</p><p class="small-note">— A note from your teacher</p><button class="primary" id="rematch" ${this.net.host?'':'disabled'}>${this.net.host?'Another lesson?':'Waiting for your host'} <span>↺</span></button><p class="small-note">Return to your room to swap studies and play again.</p><button class="text-button" id="leave">Back to title</button>`);
  this.bind();
 }
 private bind(){
  const click=(id:string,fn:()=>void)=>this.root.querySelector('#'+id)?.addEventListener('click',()=>{this.sound.start();fn();});
  click('create',()=>{void this.net.connect(true).then(()=>{this.mode='room';this.render(true);}).catch(e=>{this.net.error=String(e);this.render(true);});});
  click('join',()=>{this.mode='join';this.render();});click('back',()=>{this.mode='title';this.render();});
  click('connect',()=>{const value=(this.root.querySelector('#room-input') as HTMLInputElement).value;if(value.length!==6){this.net.error='Room codes have six letters or numbers.';this.render(true);return;}void this.net.connect(false,value).then(()=>{this.mode='room';this.render(true);}).catch(e=>{this.net.error=String(e);this.render(true);});});
  this.root.querySelector('#room-input')?.addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter')(this.root.querySelector('#connect') as HTMLButtonElement).click();});
  click('swap',()=>{this.net.intent({type:'swap'});this.net.broadcast();});click('ready',()=>{this.net.intent({type:'ready'});this.net.broadcast();});click('start',()=>{this.net.intent({type:'start'});this.net.broadcast();});
  click('copy',()=>{const u=new URL(location.href);u.searchParams.set('room',this.net.code);u.searchParams.delete('debug');void navigator.clipboard.writeText(u.href).then(()=>{const b=this.root.querySelector('#copy');if(b)b.textContent='Invite copied';}).catch(()=>{this.net.error='Copy the room code shown above.';this.render(true);});});
  click('copy-code',()=>{void navigator.clipboard.writeText(this.net.code);});
  click('pause',()=>{this.mode='pause';this.render();});click('controls',()=>{this.mode='controls';this.render();});
  click('resume',()=>{this.mode=this.net.state?.phase==='playing'?'play':'title';this.onResume();this.render(true);});click('respawn',()=>{this.onRespawn();this.mode='play';this.onResume();this.render(true);});
  click('rematch',()=>{this.net.intent({type:'rematch'});this.net.broadcast();});click('return-room',()=>{if(this.net.host){this.net.intent({type:'rematch'});this.net.broadcast();this.mode='room';this.render(true);}else{this.net.error='Ask your host to return both players to the room, or leave below.';this.render(true);}});
  click('leave',()=>{void this.net.leave().then(()=>{this.mode='title';this.onExit();this.render(true);});});
  this.root.querySelector('#volume')?.addEventListener('input',e=>this.sound.setVolume(Number((e.target as HTMLInputElement).value)));
 }
 tick(s:GameState,time:number,stats:unknown){if(this.mode!=='play')return;
  const text=(id:string,value:string)=>{const el=this.root.querySelector('#'+id);if(el)el.textContent=value;};text('chapter',chapters[s.level]);const role=this.net.local?.role??'Shaper';
  const objective=[s.done?'Take opposite brass pads. Spark together.':'Calibrate the little teaching seal.',s.done?'Cross your new bridge together.':`Guide the root to anchor ${s.step+1} of 2.`,s.done?'Step onto the far landing.':`Carry the flower to droplet ${s.step+1} of 3.`,s.done?'Spark both pressure valves together.':`Bind wheel brace ${s.step+1} of 3.`,s.done?'The spell has found its way out.':`Find living channel ${s.step+1} of 3.`,s.done?'Nearly there.':'Guide the wild green through the open arches.',s.done?'Opposite nodes. One spell, together.':`Mend ring ${s.step+1} of 3.`][s.level];text('objective',objective);text('partner-info',`${this.net.peerCount}/2 · ${Math.round(this.net.latency)} ms`);
  let hint='';let sub='';let progress=s.bloom;
  if(s.time<13&&s.level===0&&!s.done){hint='<span class="key">WASD</span> Move <span class="key">Space</span> Jump <span class="key">Shift</span> Dash';sub='Right-drag to look · Q levitates nearby ceramics · F pings your partner';}
  else if(s.level===2&&!s.flags[0]){hint='Both step onto the flower.';sub='Jump from the landing. Your partner has the other half of the controls.';}
  else if(s.level===2&&!s.done){const f=flowerPosition(s);hint=role==='Shaper'?'<span class="key">E + A / D</span> Slide the flower left / right':'<span class="key">E + W / S</span> Grow higher / settle lower';sub=`Match the glowing droplet, then either Spark (R). Height ${f.y.toFixed(1)} · target ${[3,6,4][s.step]}`;progress=0;}
  else if(s.level===4&&!s.done){hint=role==='Warden'?`Living route: ${['LEFT · 1','CENTRE · 2','RIGHT · 3'][Math.round((desired(s)+.8)/.8)]}`:'<span class="key">E + A / D</span> Guide into your partner’s living route';sub=role==='Warden'?'Tell your partner which arch. Hold E to send growth through it.':'The Warden can see the root network. Ask which arch is alive.';}
  else if(s.level===5){hint=role==='Shaper'?'<span class="key">E + A / D</span> Bend the vine toward the gold guide':'<span class="key">E + W / S</span> Grow higher / curl lower · release E to wait';sub=`Arch ${Math.min(6,s.step+1)} / 6 · ${vineAligned(s)?'The way is clear. Grow!':role==='Warden'?`Height ${s.vineHeight.toFixed(1)} · arch ${vineHeights[Math.min(5,s.step)]}. Match the glowing opening.`:'Steer into the guide. Your partner controls height.'}`;progress=s.ride/72;}
  else if(s.done){hint=s.level===0||s.level===6?'<span class="key">R</span> Spark from opposite brass pads':s.level===3?'<span class="key">R</span> Spark a pressure valve with your partner':'Follow the path you made together.';sub=s.level===0||s.level===6?'Ivo takes the left pad. Nell takes the right. Cast within three seconds.':'';progress=1;}
  else {hint=role==='Shaper'?'<span class="key">E + A / D</span> Shape · align the brass geometry':'<span class="key">E</span> Bloom · awaken the living structure';sub=aligned(s)?'Aligned. Hold Bloom to let the living geometry take shape.':role==='Shaper'?`Guide ${s.shape<desired(s)?'right →':'← left'} until the geometry aligns.`:'Your partner can give the growth a direction.';}
  if(time-this.lastRefresh>.1){this.lastRefresh=time;const el=this.root.querySelector('#hint');if(el)el.innerHTML=`${hint}${sub?`<small>${sub}</small>`:''}${progress>0?`<div class="progress"><span style="width:${Math.min(100,progress*100)}%"></span></div>`:''}`;}
  const dbg=this.root.querySelector('#debug');if(dbg)dbg.innerHTML=this.debug?`<div class="debug">${JSON.stringify(stats,null,2)}</div>`:'';
 }
 toast(text:string){const el=this.root.querySelector('#toast');if(el){el.innerHTML='';const d=document.createElement('div');d.className='toast';d.textContent=text;el.append(d);}}
}
