export class Sound {
 ctx?:AudioContext;master?:GainNode;volume=.4;muted=false;private next=0;private beat=0;
 start(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);}void this.ctx.resume();}
 setVolume(v:number){this.volume=v;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:v,this.ctx!.currentTime,.1);}
 mute(){this.muted=!this.muted;this.setVolume(this.volume);}
 tone(freq:number,duration=.2,type:OscillatorType='sine',gain=.2,delay=0){if(!this.ctx||!this.master)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,gain),t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration=.25,gain=.08){if(!this.ctx||!this.master)return;const n=this.ctx.sampleRate*duration,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='lowpass';f.frequency.value=1400;g.gain.value=gain;s.buffer=b;s.connect(f);f.connect(g);g.connect(this.master);s.start();s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
 play(kind:string){switch(kind){case 'spark':this.tone(880,.18,'triangle',.22);this.tone(1320,.3,'sine',.1,.05);break;case 'success':[440,550,660,880].forEach((f,i)=>this.tone(f,.7,'triangle',.12,i*.1));this.noise(.6,.08);break;case 'finale':[220,330,440,550,660,880,1100].forEach((f,i)=>this.tone(f,4,'sine',.18,i*.17));break;case 'jump':this.tone(260,.15,'sine',.13);break;case 'land':this.noise(.1,.12);break;case 'dash':this.noise(.23,.17);this.tone(330,.3,'sine',.08);break;case 'ping':this.tone(990,.6,'sine',.12);break;case 'hand':this.tone(330,.45,'triangle',.12);break;case 'chapter':this.tone(440,1,'sine',.12);break;default:this.tone(200,.15,'sine',.1);}}
 tick(time:number,level:number,channel:boolean){if(!this.ctx||time<this.next)return;const tense=level>=4&&level<6;this.next=time+(tense?.42:.8);const notes=tense?[146.83,220,293.66,349.23,440,293.66]:[174.61,261.63,349.23,440,523.25,440,349.23,261.63];this.tone(notes[this.beat++%notes.length],1.5,'sine',.045);if(this.beat%4===0)this.tone(tense?73.42:87.31,3,'sine',.06);if(channel){this.tone(110+Math.sin(time)*12,.5,'triangle',.035);this.noise(.3,.025);}}
}
